// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	sections "github.com/marcoglnd/mercado-fresco-packmain/internal/sections/domain"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, sectionNumber, currentTemperature, minimumTemperature, currentCapacity, minimumCapacity, maximumCapacity, warehouseId, productTypeId
func (_m *Service) Create(ctx context.Context, sectionNumber int, currentTemperature int, minimumTemperature int, currentCapacity int, minimumCapacity int, maximumCapacity int, warehouseId int, productTypeId int) (*sections.Section, error) {
	ret := _m.Called(ctx, sectionNumber, currentTemperature, minimumTemperature, currentCapacity, minimumCapacity, maximumCapacity, warehouseId, productTypeId)

	var r0 *sections.Section
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int, int, int, int, int, int) *sections.Section); ok {
		r0 = rf(ctx, sectionNumber, currentTemperature, minimumTemperature, currentCapacity, minimumCapacity, maximumCapacity, warehouseId, productTypeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sections.Section)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int, int, int, int, int, int, int) error); ok {
		r1 = rf(ctx, sectionNumber, currentTemperature, minimumTemperature, currentCapacity, minimumCapacity, maximumCapacity, warehouseId, productTypeId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Service) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *Service) GetAll(ctx context.Context) (*[]sections.Section, error) {
	ret := _m.Called(ctx)

	var r0 *[]sections.Section
	if rf, ok := ret.Get(0).(func(context.Context) *[]sections.Section); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]sections.Section)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, id
func (_m *Service) GetById(ctx context.Context, id int) (*sections.Section, error) {
	ret := _m.Called(ctx, id)

	var r0 *sections.Section
	if rf, ok := ret.Get(0).(func(context.Context, int) *sections.Section); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sections.Section)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, sectionNumber, currentTemperature, minimumTemperature, currentCapacity, minimumCapacity, maximumCapacity, warehouseId, productTypeId
func (_m *Service) Update(ctx context.Context, id int, sectionNumber int, currentTemperature int, minimumTemperature int, currentCapacity int, minimumCapacity int, maximumCapacity int, warehouseId int, productTypeId int) (*sections.Section, error) {
	ret := _m.Called(ctx, id, sectionNumber, currentTemperature, minimumTemperature, currentCapacity, minimumCapacity, maximumCapacity, warehouseId, productTypeId)

	var r0 *sections.Section
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int, int, int, int, int, int, int) *sections.Section); ok {
		r0 = rf(ctx, id, sectionNumber, currentTemperature, minimumTemperature, currentCapacity, minimumCapacity, maximumCapacity, warehouseId, productTypeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sections.Section)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int, int, int, int, int, int, int, int) error); ok {
		r1 = rf(ctx, id, sectionNumber, currentTemperature, minimumTemperature, currentCapacity, minimumCapacity, maximumCapacity, warehouseId, productTypeId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
