// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	sellers "github.com/marcoglnd/mercado-fresco-packmain/internal/sellers"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *Repository) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *Repository) GetAll() ([]sellers.Seller, error) {
	ret := _m.Called()

	var r0 []sellers.Seller
	if rf, ok := ret.Get(0).(func() []sellers.Seller); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sellers.Seller)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *Repository) GetById(id int) (sellers.Seller, error) {
	ret := _m.Called(id)

	var r0 sellers.Seller
	if rf, ok := ret.Get(0).(func(int) sellers.Seller); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(sellers.Seller)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LastID provides a mock function with given fields:
func (_m *Repository) LastID() (int, error) {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: id, cid, company_name, address, telephone
func (_m *Repository) Store(id int, cid int, company_name string, address string, telephone string) (sellers.Seller, error) {
	ret := _m.Called(id, cid, company_name, address, telephone)

	var r0 sellers.Seller
	if rf, ok := ret.Get(0).(func(int, int, string, string, string) sellers.Seller); ok {
		r0 = rf(id, cid, company_name, address, telephone)
	} else {
		r0 = ret.Get(0).(sellers.Seller)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int, string, string, string) error); ok {
		r1 = rf(id, cid, company_name, address, telephone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, cid, company_name, address, telephone
func (_m *Repository) Update(id int, cid int, company_name string, address string, telephone string) (sellers.Seller, error) {
	ret := _m.Called(id, cid, company_name, address, telephone)

	var r0 sellers.Seller
	if rf, ok := ret.Get(0).(func(int, int, string, string, string) sellers.Seller); ok {
		r0 = rf(id, cid, company_name, address, telephone)
	} else {
		r0 = ret.Get(0).(sellers.Seller)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int, string, string, string) error); ok {
		r1 = rf(id, cid, company_name, address, telephone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
