// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/marcoglnd/mercado-fresco-packmain/internal/buyers/domain"
	mock "github.com/stretchr/testify/mock"
)

// BuyerRepository is an autogenerated mock type for the BuyerRepository type
type BuyerRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, cardNumberId, firstName, lastName
func (_m *BuyerRepository) Create(ctx context.Context, cardNumberId string, firstName string, lastName string) (*domain.Buyer, error) {
	ret := _m.Called(ctx, cardNumberId, firstName, lastName)

	var r0 *domain.Buyer
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.Buyer); ok {
		r0 = rf(ctx, cardNumberId, firstName, lastName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Buyer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, cardNumberId, firstName, lastName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *BuyerRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *BuyerRepository) GetAll(ctx context.Context) (*[]domain.Buyer, error) {
	ret := _m.Called(ctx)

	var r0 *[]domain.Buyer
	if rf, ok := ret.Get(0).(func(context.Context) *[]domain.Buyer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.Buyer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByCardNumberId provides a mock function with given fields: ctx, cardNumberId
func (_m *BuyerRepository) GetByCardNumberId(ctx context.Context, cardNumberId string) (*domain.Buyer, error) {
	ret := _m.Called(ctx, cardNumberId)

	var r0 *domain.Buyer
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Buyer); ok {
		r0 = rf(ctx, cardNumberId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Buyer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cardNumberId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, id
func (_m *BuyerRepository) GetById(ctx context.Context, id int64) (*domain.Buyer, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Buyer
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Buyer); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Buyer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportAllPurchaseOrders provides a mock function with given fields: ctx
func (_m *BuyerRepository) ReportAllPurchaseOrders(ctx context.Context) (*[]domain.PurchaseOrdersResponse, error) {
	ret := _m.Called(ctx)

	var r0 *[]domain.PurchaseOrdersResponse
	if rf, ok := ret.Get(0).(func(context.Context) *[]domain.PurchaseOrdersResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.PurchaseOrdersResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportPurchaseOrders provides a mock function with given fields: ctx, buyerId
func (_m *BuyerRepository) ReportPurchaseOrders(ctx context.Context, buyerId int64) (*domain.PurchaseOrdersResponse, error) {
	ret := _m.Called(ctx, buyerId)

	var r0 *domain.PurchaseOrdersResponse
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.PurchaseOrdersResponse); ok {
		r0 = rf(ctx, buyerId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PurchaseOrdersResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, buyerId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, cardNumberId, firstName, lastName
func (_m *BuyerRepository) Update(ctx context.Context, id int64, cardNumberId string, firstName string, lastName string) (*domain.Buyer, error) {
	ret := _m.Called(ctx, id, cardNumberId, firstName, lastName)

	var r0 *domain.Buyer
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, string) *domain.Buyer); ok {
		r0 = rf(ctx, id, cardNumberId, firstName, lastName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Buyer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string, string) error); ok {
		r1 = rf(ctx, id, cardNumberId, firstName, lastName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBuyerRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewBuyerRepository creates a new instance of BuyerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBuyerRepository(t mockConstructorTestingTNewBuyerRepository) *BuyerRepository {
	mock := &BuyerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
