// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/marcoglnd/mercado-fresco-packmain/internal/purchase-orders/domain"
	mock "github.com/stretchr/testify/mock"
)

// PurchaseOrderRepository is an autogenerated mock type for the PurchaseOrderRepository type
type PurchaseOrderRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, orderNumber, orderDate, trackingCode, buyerId, carrierId, orderStatusId, warehouseId
func (_m *PurchaseOrderRepository) Create(ctx context.Context, orderNumber string, orderDate string, trackingCode string, buyerId int64, carrierId int64, orderStatusId int64, warehouseId int64) (*domain.PurchaseOrder, error) {
	ret := _m.Called(ctx, orderNumber, orderDate, trackingCode, buyerId, carrierId, orderStatusId, warehouseId)

	var r0 *domain.PurchaseOrder
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64, int64, int64, int64) *domain.PurchaseOrder); ok {
		r0 = rf(ctx, orderNumber, orderDate, trackingCode, buyerId, carrierId, orderStatusId, warehouseId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PurchaseOrder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int64, int64, int64, int64) error); ok {
		r1 = rf(ctx, orderNumber, orderDate, trackingCode, buyerId, carrierId, orderStatusId, warehouseId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByOrderNumber provides a mock function with given fields: ctx, orderNumber
func (_m *PurchaseOrderRepository) GetByOrderNumber(ctx context.Context, orderNumber string) (*domain.PurchaseOrder, error) {
	ret := _m.Called(ctx, orderNumber)

	var r0 *domain.PurchaseOrder
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.PurchaseOrder); ok {
		r0 = rf(ctx, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PurchaseOrder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPurchaseOrderRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewPurchaseOrderRepository creates a new instance of PurchaseOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPurchaseOrderRepository(t mockConstructorTestingTNewPurchaseOrderRepository) *PurchaseOrderRepository {
	mock := &PurchaseOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
