// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	products "github.com/marcoglnd/mercado-fresco-packmain/internal/products"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateNewProduct provides a mock function with given fields: ctx, product
func (_m *Repository) CreateNewProduct(ctx context.Context, product *products.Product) (*products.Product, error) {
	ret := _m.Called(ctx, product)

	var r0 *products.Product
	if rf, ok := ret.Get(0).(func(context.Context, *products.Product) *products.Product); ok {
		r0 = rf(ctx, product)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*products.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *products.Product) error); ok {
		r1 = rf(ctx, product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *Repository) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *Repository) GetAll() ([]products.Product, error) {
	ret := _m.Called()

	var r0 []products.Product
	if rf, ok := ret.Get(0).(func() []products.Product); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]products.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *Repository) GetById(id int) (products.Product, error) {
	ret := _m.Called(id)

	var r0 products.Product
	if rf, ok := ret.Get(0).(func(int) products.Product); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(products.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LastId provides a mock function with given fields:
func (_m *Repository) LastId() (int, error) {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, description, expirationRate, freezingRate, height, length, netWeight, productCode, recommendedFreezingTemperature, width, productTypeId, sellerId
func (_m *Repository) Update(id int, description string, expirationRate int, freezingRate int, height float64, length float64, netWeight float64, productCode string, recommendedFreezingTemperature float64, width float64, productTypeId int, sellerId int) (products.Product, error) {
	ret := _m.Called(id, description, expirationRate, freezingRate, height, length, netWeight, productCode, recommendedFreezingTemperature, width, productTypeId, sellerId)

	var r0 products.Product
	if rf, ok := ret.Get(0).(func(int, string, int, int, float64, float64, float64, string, float64, float64, int, int) products.Product); ok {
		r0 = rf(id, description, expirationRate, freezingRate, height, length, netWeight, productCode, recommendedFreezingTemperature, width, productTypeId, sellerId)
	} else {
		r0 = ret.Get(0).(products.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string, int, int, float64, float64, float64, string, float64, float64, int, int) error); ok {
		r1 = rf(id, description, expirationRate, freezingRate, height, length, netWeight, productCode, recommendedFreezingTemperature, width, productTypeId, sellerId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
