// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	products "github.com/marcoglnd/mercado-fresco-packmain/internal/products"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateNewProduct provides a mock function with given fields: description, expirationRate, freezingRate, height, length, netWeight, productCode, recommendedFreezingTemperature, width, productTypeId, sellerId
func (_m *Service) CreateNewProduct(description string, expirationRate int, freezingRate int, height float64, length float64, netWeight float64, productCode string, recommendedFreezingTemperature float64, width float64, productTypeId int, sellerId int) (products.Product, error) {
	ret := _m.Called(description, expirationRate, freezingRate, height, length, netWeight, productCode, recommendedFreezingTemperature, width, productTypeId, sellerId)

	var r0 products.Product
	if rf, ok := ret.Get(0).(func(string, int, int, float64, float64, float64, string, float64, float64, int, int) products.Product); ok {
		r0 = rf(description, expirationRate, freezingRate, height, length, netWeight, productCode, recommendedFreezingTemperature, width, productTypeId, sellerId)
	} else {
		r0 = ret.Get(0).(products.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int, int, float64, float64, float64, string, float64, float64, int, int) error); ok {
		r1 = rf(description, expirationRate, freezingRate, height, length, netWeight, productCode, recommendedFreezingTemperature, width, productTypeId, sellerId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *Service) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *Service) GetAll() ([]products.Product, error) {
	ret := _m.Called()

	var r0 []products.Product
	if rf, ok := ret.Get(0).(func() []products.Product); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]products.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *Service) GetById(id int) (products.Product, error) {
	ret := _m.Called(id)

	var r0 products.Product
	if rf, ok := ret.Get(0).(func(int) products.Product); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(products.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, description, expirationRate, freezingRate, height, length, netWeight, productCode, recommendedFreezingTemperature, width, productTypeId, sellerId
func (_m *Service) Update(id int, description string, expirationRate int, freezingRate int, height float64, length float64, netWeight float64, productCode string, recommendedFreezingTemperature float64, width float64, productTypeId int, sellerId int) (products.Product, error) {
	ret := _m.Called(id, description, expirationRate, freezingRate, height, length, netWeight, productCode, recommendedFreezingTemperature, width, productTypeId, sellerId)

	var r0 products.Product
	if rf, ok := ret.Get(0).(func(int, string, int, int, float64, float64, float64, string, float64, float64, int, int) products.Product); ok {
		r0 = rf(id, description, expirationRate, freezingRate, height, length, netWeight, productCode, recommendedFreezingTemperature, width, productTypeId, sellerId)
	} else {
		r0 = ret.Get(0).(products.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string, int, int, float64, float64, float64, string, float64, float64, int, int) error); ok {
		r1 = rf(id, description, expirationRate, freezingRate, height, length, netWeight, productCode, recommendedFreezingTemperature, width, productTypeId, sellerId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
