definitions:
  controllers.requestSellers:
    properties:
      address:
        type: string
      cid:
        type: integer
      company_name:
        type: string
      telephone:
        type: integer
    type: object
  schemes.JSONBadReqResult:
    properties:
      error: {}
    type: object
  schemes.JSONSuccessResult:
    properties:
      data: {}
    type: object
  schemes.Seller:
    properties:
      adress:
        type: string
      cid:
        type: integer
      company_name:
        type: string
      id:
        type: integer
      telephone:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    name: API Support
    url: https://developers.mercadolibre.com.ar/support
  description: This API Handle MELI Products.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developers.mercadolibre.com.ar/es_ar/terminos-y-condiciones
  title: MERCADO FRESCOS
  version: "1.0"
paths:
  /sellers:
    get:
      consumes:
      - application/json
      description: get all sellers
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONSuccessResult'
            - properties:
                data:
                  $ref: '#/definitions/schemes.Seller'
              type: object
        "404":
          description: Not Found
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONBadReqResult'
            - properties:
                error:
                  type: string
              type: object
      summary: List sellers
      tags:
      - Sellers
    post:
      consumes:
      - application/json
      description: Add a new Seller to the list
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: seller to create
        in: body
        name: Seller
        required: true
        schema:
          $ref: '#/definitions/controllers.requestSellers'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONSuccessResult'
            - properties:
                data:
                  $ref: '#/definitions/schemes.Seller'
              type: object
        "404":
          description: Not Found
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONBadReqResult'
            - properties:
                error:
                  type: string
              type: object
        "422":
          description: Unprocessable Entity
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONBadReqResult'
            - properties:
                error:
                  type: string
              type: object
      summary: Create seller
      tags:
      - Sellers
  /sellers/{id}:
    delete:
      consumes:
      - application/json
      description: Delete existing seller in list
      parameters:
      - description: Seller ID
        in: path
        name: id
        required: true
        type: integer
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONSuccessResult'
            - properties:
                data:
                  $ref: '#/definitions/schemes.Seller'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONBadReqResult'
            - properties:
                error:
                  type: string
              type: object
        "404":
          description: Not Found
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONBadReqResult'
            - properties:
                error:
                  type: string
              type: object
      summary: Delete seller
      tags:
      - Sellers
    get:
      consumes:
      - application/json
      description: get Seller by it's id
      parameters:
      - description: Seller ID
        in: path
        name: id
        required: true
        type: integer
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONSuccessResult'
            - properties:
                data:
                  $ref: '#/definitions/schemes.Seller'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONBadReqResult'
            - properties:
                error:
                  type: string
              type: object
        "404":
          description: Not Found
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONBadReqResult'
            - properties:
                error:
                  type: string
              type: object
      summary: Seller by id
      tags:
      - Sellers
    patch:
      consumes:
      - application/json
      description: Update existing Seller in list
      parameters:
      - description: Seller ID
        in: path
        name: id
        required: true
        type: integer
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Seller to update
        in: body
        name: seller
        required: true
        schema:
          $ref: '#/definitions/controllers.requestSellers'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONSuccessResult'
            - properties:
                data:
                  $ref: '#/definitions/schemes.Seller'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONBadReqResult'
            - properties:
                error:
                  type: string
              type: object
        "404":
          description: Not Found
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONBadReqResult'
            - properties:
                error:
                  type: string
              type: object
      summary: Update seller
      tags:
      - Sellers
swagger: "2.0"
