definitions:
  schemes.JSONBadReqResult:
    properties:
      error: {}
    type: object
  schemes.JSONSuccessResult:
    properties:
      data: {}
    type: object
  warehouses.CreateWarehouseInput:
    properties:
      address:
        type: string
      minimum_capacity:
        minimum: 1
        type: integer
      minimum_temperature:
        minimum: 1
        type: integer
      telephone:
        type: string
      warehouse_code:
        type: string
    required:
    - address
    - minimum_capacity
    - minimum_temperature
    - telephone
    - warehouse_code
    type: object
  warehouses.UpdateWarehouseInput:
    properties:
      address:
        type: string
      minimum_capacity:
        minimum: 0
        type: integer
      minimum_temperature:
        minimum: 0
        type: integer
      telephone:
        type: string
      warehouse_code:
        type: string
    type: object
  warehouses.Warehouse:
    properties:
      address:
        type: string
      id:
        type: integer
      minimum_capacity:
        minimum: 1
        type: integer
      minimum_temperature:
        minimum: 1
        type: integer
      telephone:
        type: string
      warehouse_code:
        type: string
    required:
    - address
    - minimum_capacity
    - minimum_temperature
    - telephone
    - warehouse_code
    type: object
host: localhost:8080
info:
  contact:
    name: API Support
    url: https://developers.mercadolibre.com.ar/support
  description: This API Handle MELI Products.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developers.mercadolibre.com.ar/es_ar/terminos-y-condiciones
  title: MERCADO FRESCOS
  version: "1.0"
paths:
  /warehouses:
    get:
      consumes:
      - application/json
      description: get all warehouses
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONSuccessResult'
            - properties:
                data:
                  $ref: '#/definitions/warehouses.Warehouse'
              type: object
        "422":
          description: Unprocessable Entity
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONBadReqResult'
            - properties:
                error:
                  type: string
              type: object
      summary: List warehouses
      tags:
      - Warehouses
    post:
      consumes:
      - application/json
      description: Add a new warehouse checking for duplicate warehouses code before
      parameters:
      - description: Warehouse to create
        in: body
        name: warehouse
        required: true
        schema:
          $ref: '#/definitions/warehouses.CreateWarehouseInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONSuccessResult'
            - properties:
                data:
                  $ref: '#/definitions/warehouses.Warehouse'
              type: object
        "422":
          description: Unprocessable Entity
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONBadReqResult'
            - properties:
                error:
                  type: string
              type: object
      summary: Create warehouse
      tags:
      - Warehouses
  /warehouses/{id}:
    delete:
      consumes:
      - application/json
      description: Delete existing warehouse in list
      parameters:
      - description: warehouse ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONSuccessResult'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONBadReqResult'
            - properties:
                error:
                  type: string
              type: object
        "404":
          description: Not Found
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONBadReqResult'
            - properties:
                error:
                  type: string
              type: object
      summary: Delete warehouse
      tags:
      - Warehouses
    get:
      consumes:
      - application/json
      description: get warehouse by it's id
      parameters:
      - description: Warehouse ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONSuccessResult'
            - properties:
                data:
                  $ref: '#/definitions/warehouses.Warehouse'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONBadReqResult'
            - properties:
                error:
                  type: string
              type: object
        "404":
          description: Not Found
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONBadReqResult'
            - properties:
                error:
                  type: string
              type: object
      summary: Warehouse by id
      tags:
      - Warehouses
    patch:
      consumes:
      - application/json
      description: Update existing warehouse in list checking for duplicate warehouses
        code
      parameters:
      - description: Warehouse ID
        in: path
        name: id
        required: true
        type: integer
      - description: Warehouse to update
        in: body
        name: warehouse
        required: true
        schema:
          $ref: '#/definitions/warehouses.UpdateWarehouseInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONSuccessResult'
            - properties:
                data:
                  $ref: '#/definitions/warehouses.Warehouse'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONBadReqResult'
            - properties:
                error:
                  type: string
              type: object
        "404":
          description: Not Found
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONBadReqResult'
            - properties:
                error:
                  type: string
              type: object
        "422":
          description: Unprocessable Entity
          schema:
            allOf:
            - $ref: '#/definitions/schemes.JSONBadReqResult'
            - properties:
                error:
                  type: string
              type: object
      summary: Update warehouse
      tags:
      - Warehouses
swagger: "2.0"
